variable "project_name" {}
variable "public_subnets_id" {}
variable "private_subnets_id" {}
variable "instance_type" {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "vpc_id" {}
variable "eks_inb_ports" {}