---
name: Build and Push Webserver to ECR
on:
  push:
    paths:
      - 'app-code/**'
    branches:
    - 'dev-**'
    - 'fix-**'
    
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push image to registry
      id: build-push
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: nt-project-dev/webserver
        IMAGE_TAG: 
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF_NAME} -f ./app-code/Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF_NAME}
    
    - name: Deploy to test env
      id: deploy-to-test
      run: |
        echo "Deploy to test env"

    - name: Deploy to test stage
      id: deploy-to-stage
      run: |
        echo "Deploy to stage env"